services:
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_PASSWORD=123
    ports:
      - 5432
  sync:
    build:
      context: .
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_HOST=db
    depends_on:
      - db
      - filesync # This is a bit of a hack, so running the exercises starts the filesync
    tty: true  # Allow the filesync to print output to the console
    volumes:
      - ./lib:/app/lib
      - ./exercises:/app/exercises
  filesync:
    image: ghcr.io/skiller-whale/learnersync:0.2.1
    environment:
      SERVER_URL: https://train.skillerwhale.com/
      SW_RUNNING_IN_HOSTED_ENV:
      WATCHER_BASE_PATH: /app
      ATTENDANCE_ID_FILE: /app/sync/attendance_id
      WATCHED_EXTS: .sql
      IGNORE_MATCH: .git
    volumes:
      - ./exercises:/app/exercises
      - ./attendance_id:/app/sync/attendance_id
