#! /usr/bin/env python3

import threading
import time


from lib.pg_exec import PgExec
from lib.watcher import Watcher


OUTPUT_LOCK = threading.Lock()

# These names should match the folder names in exercises and db_init
DATABASE_NAMES = [
    'album_sales',
    'sales_global'
]

def pg_update():
    time.sleep(1)  # Give time for the database service to start
    pg_executor = PgExec(DATABASE_NAMES, output_lock=OUTPUT_LOCK)
    watcher = Watcher(pg_executor, base_path="exercises", output_lock=OUTPUT_LOCK)
    while True:
        try:
            watcher.poll_for_changes()
        except BaseException as err:
            print(f"Unexpected error with postgres auto-runner: {err}")
            time.sleep(1)
            print(f"Restarting...")


if __name__ == "__main__":
    pg_update()
