-- Any query you write in here will be run against the
-- album sales database when you save the file.
--
-- The database will be reset after each query, so you don't
-- need to worry about deleting or modifying any data!
